name: Prettier

on:
  pull-request:

env:
  FILE_PATTERN: "src/**/*.{ts,tsx,js,jsx}"

jobs:
  lint:
    runs-on: ubuntsu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node
        with:
          node-version: 16.13
      - name: Run Prettier
        run: |
          npm install
          npx prettier -w ${FILE_PATTERN}
      - name: Commit Formatted Code
        run: |
          git add .
          git commit -m 'Add GitHub Actions'
          git push origin main
