name: Prettier

on:
  pull_request:

env:
  FILE_PATTERN: "src/**/*.{ts,tsx,js,jsx}"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16.13
      - name: Run Prettier
        run: |
          npm install
          npx prettier -w ${FILE_PATTERN}
      - name: Commit Formatted Code
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m '[format] Prettierでフォーマットを実行'
          git push origin HEAD
